const { validateKnowledgeBase } = require("./omsKnowledgeBase.schema");
const {
  ambiguousConcepts,
  businessConceptMappings,
  capabilities,
  legacyAliases,
  uncertainties,
} = require("./omsKnowledgeBase.capabilities");

const src = (path, ...symbols) => ({ path, symbols });
const freeze = (value) => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  Object.values(value).forEach(freeze);
  return value;
};
const collection = (id, name, domain, description, fields, sources, certainty = "verified", extra = {}) => ({
  id,
  collection: name,
  domain,
  description,
  importantFields: fields,
  sources,
  certainty,
  ...extra,
});
const relation = (id, from, to, description, sources, certainty = "verified", extra = {}) => ({
  id,
  from,
  to,
  description,
  sources,
  certainty,
  ...extra,
});

const catalog = {
  version: "2.0.0",
  title: "OMS Knowledge Base",
  scope: {
    step: "knowledge_base_v2",
    auditCapabilityCount: 74,
    assistantIntegration: "metadata_ready_for_next_capability_execution_phase",
    existingCapabilityAdapters: ["packed_goods", "monthly_shipments", "shipment_cbm"],
    behaviorChange: false,
    generatedFrom: "docs/OMS_REPORTS_AND_FUNCTIONS_SUMMARY.md; runtime data was not queried",
  },
  domains: [
    { id: "order_management", name: "Order management", description: "Purchase-order intake, lifecycle, archive, ETD, and status." },
    { id: "shipment_logistics", name: "Shipment and logistics", description: "Shipment rows, containers, shipping status, packed goods, and CBM." },
    { id: "quality_control", name: "Quality control", description: "QC requests, inspections, quantities, inspection reports, and label operations." },
    { id: "catalog_master_data", name: "Catalog and master data", description: "Item identity, master catalog records, brands, vendors, and finishes." },
    { id: "product_information", name: "PIS and product data", description: "PIS, Product Database, master measurements, templates, and comparison workflows." },
    { id: "samples", name: "Samples", description: "Sample tracking, sample shipment, conversion, and separate sample workflows." },
    { id: "workflow", name: "Workflow", description: "Workflow batches, tasks, assignments, status history, departments, and comments." },
    { id: "complaints", name: "Complaints", description: "Customer/vendor complaint records, categories, comments, and files." },
    { id: "communication", name: "Communication", description: "Notifications and order-linked email logs." },
    { id: "reporting_exports", name: "Reporting and exports", description: "Read-only report endpoints, workbook exports, and PDF rendering." },
    { id: "access_security", name: "Access and security", description: "Users, roles, permissions, sessions, and security monitoring." },
    { id: "audit_history", name: "Audit and history", description: "Import, edit, and product-information audit records." },
    { id: "platform_operations", name: "Platform operations", description: "Queues, jobs, storage processing, cache, and scheduled maintenance." },
    { id: "assistant_platform", name: "Assistant platform", description: "OMS Assistant conversations, rate limits, provider, and analytics metadata." },
  ],
  collections: [
    collection("orders", "orders", "order_management", "Purchase-order line documents with embedded item, vendor, shipment, ETD, QC link, archive, and cached CBM state.", ["order_id", "item.item_code", "brand", "vendor.vendor_id", "quantity", "status", "shipment", "qc_record", "ETD", "revised_ETD", "total_po_cbm", "archived"], [src("backend/models/order.model.js", "Order_Schema"), src("backend/helpers/orderStatus.js", "deriveOrderProgress")]),
    collection("items", "items", "catalog_master_data", "Item master documents, including inspected, PIS, master, Product Database, barcode, vendor, file, and CBM fields.", ["code", "name", "description", "brand", "vendors", "inspected_item_sizes", "pis_item_sizes", "master_item_sizes", "pd_item_sizes", "product_type", "product_specs", "cbm"], [src("backend/models/item.model.js", "Item")]),
    collection("qcs", "qcs", "quality_control", "QC requests with order metadata snapshots, inspection references, request history, quantities, barcode, images, and checked state.", ["order", "order_meta.order_id", "order_meta.brand", "order_meta.vendor", "item.item_code", "inspection_record", "request_history", "quantities"], [src("backend/models/qc.model.js", "qc")]),
    collection("inspections", "inspections", "quality_control", "Inspection visits/results linked to QC records with quantity, measurement, barcode, CBM, and goods-not-ready state.", ["qc", "inspection_date", "status", "checked", "passed", "rejected", "pending_after", "inspected_item_sizes", "inspected_box_sizes", "cbm"], [src("backend/models/inspection.model.js", "InspectionSchema")]),
    collection("brands", "brands", "catalog_master_data", "Brand identity, logo, and calendar settings.", ["name", "logo", "calendar"], [src("backend/models/brand.model.js")]),
    collection("vendors", "vendors", "catalog_master_data", "Vendor identity, contacts, country, brand mappings, codes, shipping time, and active/deleted state.", ["name", "country", "vendor_code", "brands.brand_id", "brands.brand_name", "default_shipping_time", "is_active"], [src("backend/models/vendor.model.js", "Vendor")]),
    collection("samples", "samples", "samples", "Samples with vendor/brand snapshots, quantities, files, shipments, CBM, and optional converted item.", ["code", "brand", "vendor", "shipment", "cbm", "converted_item.item", "converted_item.code"], [src("backend/models/sample.model.js")]),
    collection("sample_workflows", "sample_workflows", "samples", "Separate sample-workflow records; this is not the generic workflow task system.", ["code", "brand", "vendor", "status", "shipment", "files"], [src("backend/models/sampleWorkflow.model.js", "SampleWorkflow")]),
    collection("finishes", "finishes", "catalog_master_data", "Finish references, vendor-item associations, and finish images.", ["name", "vendor", "item_code", "front_image", "back_image"], [src("backend/models/finish.model.js")], "strongly_inferred"),
    collection("product_type_templates", "product_type_templates", "product_information", "Versioned dynamic Product Database template definitions, groups, fields, and import header mappings.", ["key", "label", "version", "status", "groups.fields", "groups.fields.source_headers"], [src("backend/models/productTypeTemplate.model.js"), src("backend/helpers/productTypeTemplates.js")]),
    collection("pis_update_logs", "pis_update_logs", "audit_history", "Append-only PIS, Product Database, and master item change logs including before/after and missing-field state.", ["item_id", "item_code", "operation", "data_scope", "changed_fields", "missing_fields", "actor"], [src("backend/models/pisUpdateLog.model.js"), src("backend/helpers/itemUpdateAudit.js")]),
    collection("upload_logs", "upload_logs", "audit_history", "Order upload/import job history and source file results.", ["file_name", "uploaded_by", "status", "createdAt"], [src("backend/models/uploadLog.model.js")]),
    collection("order_edit_logs", "order_edit_logs", "audit_history", "Order edit history; it records changes but is not the order source of truth.", ["order", "order_id", "changes", "edited_by", "createdAt"], [src("backend/models/orderEditLog.model.js")]),
    collection("qc_edit_logs", "qc_edit_logs", "audit_history", "QC edit history; it records changes but is not the live QC source of truth.", ["qc", "changes", "edited_by", "createdAt"], [src("backend/models/qcEditLog.model.js")]),
    collection("complaints", "complaints", "complaints", "Complaint records with brand/vendor/item/PO context, comments, files, read receipts, and archival state.", ["complaint_no", "brand", "vendor", "item_code", "po", "category", "comments", "files", "archived"], [src("backend/models/complaint.model.js", "Complaint")]),
    collection("complaint_categories", "complaint_categories", "complaints", "Reusable complaint category labels.", ["name", "is_active"], [src("backend/models/complaintCategory.model.js", "ComplaintCategory")]),
    collection("inspectors", "inspectors", "quality_control", "Inspector profile and label allocation records; access is sensitive and not Assistant-ready.", ["user", "name", "labels", "is_active"], [src("backend/models/inspector.model.js")]),
    collection("workflow_batches", "workflow_batches", "workflow", "Workflow batch headers grouping workflow tasks.", ["batch_no", "brand", "status", "task_count", "created_by"], [src("backend/models/workflow/Batch.model.js")]),
    collection("workflow_tasks", "workflow_tasks", "workflow", "Workflow task source of truth for status, assignees, due dates, rework, upload, hold, and source files.", ["batch", "task_no", "task_type", "department", "brand", "status", "assigned_to", "due_date", "hold", "reworked"], [src("backend/models/workflow/Task.model.js")]),
    collection("workflow_task_types", "workflow_task_types", "workflow", "Configured workflow task-type definitions and stage policy.", ["key", "name", "department", "is_active"], [src("backend/models/workflow/TaskType.model.js")]),
    collection("workflow_departments", "workflow_departments", "workflow", "Workflow department definitions.", ["key", "name", "is_active"], [src("backend/models/workflow/Department.model.js")]),
    collection("workflow_task_assignments", "workflow_task_assignments", "workflow", "Assignment history for workflow tasks.", ["task", "user", "assigned_by", "assigned_at"], [src("backend/models/workflow/TaskAssignment.model.js")]),
    collection("workflow_task_status_history", "workflow_task_status_history", "workflow", "Append-only workflow task status transitions.", ["task", "batch", "from_status", "to_status", "changed_by", "changed_at"], [src("backend/models/workflow/TaskStatusHistory.model.js")]),
    collection("workflow_comments", "workflow_comments", "workflow", "Comments attached to workflow tasks.", ["task", "comment", "created_by", "created_at"], [src("backend/models/workflow/Comment.model.js")]),
    collection("notifications", "notifications", "communication", "Per-user workflow/system notifications, read/archive state, and deep links.", ["user", "type", "title", "category", "priority", "read", "entity_type", "entity_id"], [src("backend/models/notification.model.js", "Notification")]),
    collection("email_logs", "emaillogs", "communication", "Order-linked email/contact log with brand and vendor snapshots.", ["order_id", "brand.name", "brand.id", "vendor", "log", "created_by", "creation_date"], [src("backend/models/emailLogs.model.js")], "strongly_inferred", { modelName: "emailLogs" }),
    collection("users", "users", "access_security", "User identities and scope/permission inputs; sensitive and excluded from future analytical tool access unless explicitly designed.", ["name", "email", "role", "allowed_brands", "allowed_vendors", "brand_scope"], [src("backend/models/user.model.js")]),
    collection("role_permissions", "rolepermissions", "access_security", "Role permission configuration and audit history; sensitive control-plane data.", ["role", "permissions", "history", "updated_by"], [src("backend/models/rolePermission.model.js")], "strongly_inferred", { modelName: "RolePermission" }),
    collection("auth_sessions", "auth_sessions", "access_security", "Authentication sessions; sensitive and excluded from business-query use.", ["user", "token_hash", "expires_at"], [src("backend/models/authSession.model.js")]),
    collection("security_activity_logs", "security_activity_logs", "access_security", "Security/audit activity events; sensitive operational records.", ["actor", "action", "resource", "metadata", "createdAt"], [src("backend/models/securityActivityLog.model.js")]),
    collection("security_alerts", "security_alerts", "access_security", "Security monitoring alerts and status.", ["user", "severity", "status", "metadata", "createdAt"], [src("backend/models/securityAlert.model.js")]),
    collection("user_security_baselines", "user_security_baselines", "access_security", "Per-user security baselines; sensitive operational records.", ["user", "baseline", "calculated_at"], [src("backend/models/userSecurityBaseline.model.js")]),
    collection("oms_chat_conversations", "oms_chat_conversations", "assistant_platform", "Short-lived Assistant conversations; never business-report source data.", ["conversation_id", "user", "history", "expires_at"], [src("backend/models/omsChatConversation.model.js")]),
    collection("oms_chat_rate_buckets", "oms_chat_rate_buckets", "assistant_platform", "Assistant rate-limit counters; never business-report source data.", ["_id", "count", "expires_at"], [src("backend/models/omsChatRateBucket.model.js")]),
  ],
  capabilities,
  relationships: [
    relation("order_item_code", { collection: "orders", field: "item.item_code" }, { collection: "items", field: "code" }, "Order item code links an order line to its item master record.", [src("backend/models/order.model.js"), src("backend/models/item.model.js")], "verified", { cardinality: "many_to_one", join: "logical_code", role: "master_measurement_pis_product_source" }),
    relation("order_qc_record", { collection: "orders", field: "qc_record" }, { collection: "qcs", field: "_id" }, "An order may reference its current QC/progress source.", [src("backend/models/order.model.js"), src("backend/models/qc.model.js")], "verified", { cardinality: "one_to_one_or_many", role: "current_quality_and_progress_source" }),
    relation("qc_order", { collection: "qcs", field: "order" }, { collection: "orders", field: "_id" }, "QC records reference their source order.", [src("backend/models/qc.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("qc_item_code", { collection: "qcs", field: "item.item_code" }, { collection: "items", field: "code" }, "QC item snapshot code links logically to the item master.", [src("backend/models/qc.model.js"), src("backend/models/item.model.js")], "verified", { cardinality: "many_to_one", join: "logical_code" }),
    relation("qc_inspection_records", { collection: "qcs", field: "inspection_record[]" }, { collection: "inspections", field: "_id" }, "QC holds references to inspection event/snapshot history.", [src("backend/models/qc.model.js"), src("backend/models/inspection.model.js")], "verified", { cardinality: "one_to_many", role: "inspection_event_and_snapshot_history" }),
    relation("inspection_qc", { collection: "inspections", field: "qc" }, { collection: "qcs", field: "_id" }, "Inspection records reference their parent QC record.", [src("backend/models/inspection.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("order_vendor", { collection: "orders", field: "vendor.vendor_id" }, { collection: "vendors", field: "_id" }, "Order embeds a normalized vendor identity reference while retaining vendor snapshot fields.", [src("backend/models/order.model.js"), src("backend/helpers/vendorRef.js")], "verified", { cardinality: "many_to_one", join: "embedded_reference", role: "vendor_identity" }),
    relation("item_vendor", { collection: "items", field: "vendors[].vendor_id" }, { collection: "vendors", field: "_id" }, "Item vendors are normalized embedded references.", [src("backend/models/item.model.js"), src("backend/helpers/vendorRef.js")], "verified", { cardinality: "many_to_many", join: "embedded_reference" }),
    relation("vendor_brand", { collection: "vendors", field: "brands[].brand_id" }, { collection: "brands", field: "_id" }, "Vendor brand mappings reference brand documents.", [src("backend/models/vendor.model.js"), src("backend/models/brand.model.js")], "verified", { cardinality: "many_to_many" }),
    relation("order_brand_name", { collection: "orders", field: "brand" }, { collection: "brands", field: "name" }, "Order stores a brand-name snapshot rather than a Brand ObjectId.", [src("backend/models/order.model.js"), src("backend/models/brand.model.js")], "strongly_inferred", { cardinality: "many_to_one", join: "logical_name_snapshot" }),
    relation("sample_converted_item", { collection: "samples", field: "converted_item.item" }, { collection: "items", field: "_id" }, "A converted sample may point to its created item.", [src("backend/models/sample.model.js"), src("backend/controllers/sample.controller.js", "convertToItem")], "verified", { cardinality: "zero_or_one_to_one" }),
    relation("sample_vendor", { collection: "samples", field: "vendor[].vendor_id" }, { collection: "vendors", field: "_id" }, "Samples retain normalized embedded vendor references.", [src("backend/models/sample.model.js"), src("backend/helpers/vendorRef.js")], "verified", { cardinality: "many_to_many", join: "embedded_reference" }),
    relation("order_shipment_entries", { collection: "orders", field: "_id" }, { collection: "orders", field: "shipment[]" }, "Physical order shipment entries are embedded under their order document.", [src("backend/models/order.model.js")], "verified", { cardinality: "one_to_many_embedded", join: "embedded", role: "physical_shipment_evidence" }),
    relation("sample_shipment_entries", { collection: "samples", field: "_id" }, { collection: "samples", field: "shipment[]" }, "Physical sample shipment entries are embedded under their sample document.", [src("backend/models/sample.model.js")], "verified", { cardinality: "one_to_many_embedded", join: "embedded", role: "physical_sample_shipment_evidence" }),
    relation("complaint_vendor", { collection: "complaints", field: "vendor.vendor_id" }, { collection: "vendors", field: "_id" }, "Complaints embed a normalized vendor reference.", [src("backend/models/complaint.model.js"), src("backend/helpers/vendorRef.js")], "verified", { cardinality: "many_to_one", join: "embedded_reference" }),
    relation("complaint_item", { collection: "complaints", field: "item_code" }, { collection: "items", field: "code" }, "Complaint item code links logically to item master data.", [src("backend/models/complaint.model.js"), src("backend/models/item.model.js")], "verified", { cardinality: "many_to_one", join: "logical_code" }),
    relation("workflow_task_batch", { collection: "workflow_tasks", field: "batch" }, { collection: "workflow_batches", field: "_id" }, "Workflow tasks optionally belong to a workflow batch.", [src("backend/models/workflow/Task.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("workflow_task_type", { collection: "workflow_tasks", field: "task_type" }, { collection: "workflow_task_types", field: "_id" }, "Workflow tasks reference task types.", [src("backend/models/workflow/Task.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("workflow_task_department", { collection: "workflow_tasks", field: "department" }, { collection: "workflow_departments", field: "_id" }, "Workflow tasks optionally reference departments.", [src("backend/models/workflow/Task.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("workflow_assignment_task", { collection: "workflow_task_assignments", field: "task" }, { collection: "workflow_tasks", field: "_id" }, "Workflow task-assignment history references the task.", [src("backend/models/workflow/TaskAssignment.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("workflow_status_history_task", { collection: "workflow_task_status_history", field: "task" }, { collection: "workflow_tasks", field: "_id" }, "Workflow status history references the task.", [src("backend/models/workflow/TaskStatusHistory.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("workflow_comment_task", { collection: "workflow_comments", field: "task" }, { collection: "workflow_tasks", field: "_id" }, "Workflow comments reference the task.", [src("backend/models/workflow/Comment.model.js")], "verified", { cardinality: "many_to_one" }),
    relation("notification_user", { collection: "notifications", field: "user" }, { collection: "users", field: "_id" }, "Notifications are user-scoped.", [src("backend/models/notification.model.js")], "verified", { cardinality: "many_to_one", access: "sensitive" }),
    relation("email_log_order", { collection: "email_logs", field: "order_id" }, { collection: "orders", field: "order_id" }, "Email logs link logically to an order ID.", [src("backend/models/emailLogs.model.js"), src("backend/models/order.model.js")], "verified", { cardinality: "many_to_one", join: "logical_code", access: "sensitive" }),
    relation("audit_order_edit", { collection: "order_edit_logs", field: "order" }, { collection: "orders", field: "_id" }, "Order edit records point at the live order they describe.", [src("backend/models/orderEditLog.model.js")], "verified", { cardinality: "many_to_one", role: "audit_only" }),
    relation("audit_qc_edit", { collection: "qc_edit_logs", field: "qc" }, { collection: "qcs", field: "_id" }, "QC edit records point at the live QC record they describe.", [src("backend/models/qcEditLog.model.js")], "verified", { cardinality: "many_to_one", role: "audit_only" }),
  ],
  sourceOfTruthRules: [
    { id: "orders_live_state", description: "Live order facts come from orders; edit/archive logs are history only.", canonicalSource: "orders", sources: [src("backend/models/order.model.js"), src("backend/models/orderEditLog.model.js")], certainty: "verified" },
    { id: "order_progress_derivation", description: "Use deriveOrderProgress for current analytical PO progress/status rather than only orders.status.", canonicalSource: "backend/helpers/orderStatus.js#deriveOrderProgress", sources: [src("backend/helpers/orderStatus.js")], certainty: "verified" },
    { id: "packed_goods_dataset", description: "Assistant and forecast ready-to-ship Packed Goods use buildPackedGoodsDataset and intentionally retain their current semantics.", canonicalSource: "backend/services/packedGoods.service.js#buildPackedGoodsDataset", sources: [src("backend/services/packedGoods.service.js"), src("backend/services/omsCapabilityExecution.service.js")], certainty: "verified" },
    { id: "packed_goods_period_report", description: "The Packed Goods page/API/PDF/XLS report is built from qualifying Inspection history in the selected inclusive period.", canonicalSource: "backend/services/packedGoodsPeriod.service.js#buildPackedGoodsPeriodDataset", sources: [src("backend/services/packedGoodsPeriod.service.js"), src("backend/controllers/order.controller.js"), src("backend/models/inspection.model.js")], certainty: "verified" },
    { id: "shipment_cbm_calculation", description: "Use shipmentCbmAllocation/orderCbm calculations. Stored orders.total_po_cbm is a final fallback/cache, not preferred raw measurement evidence.", canonicalSource: "backend/services/shipmentCbmAllocation.service.js", sources: [src("backend/services/shipmentCbmAllocation.service.js"), src("backend/services/orderCbm.service.js")], certainty: "verified" },
    { id: "quality_live_state", description: "Current QC and inspection facts come from qcs and inspections; QC edit logs are history only.", canonicalSource: "qcs and inspections", sources: [src("backend/models/qc.model.js"), src("backend/models/inspection.model.js"), src("backend/models/qcEditLog.model.js")], certainty: "verified" },
    { id: "item_measurement_hierarchy", description: "Use the reference source selected by each audited comparison. Final PIS Check currently requires Master evidence, compares current Inspected versus Master, requires three distinct valid inspected POs, and has no PIS fallback.", canonicalSource: "items measurement arrays plus the capability-specific comparison helper", sources: [src("backend/models/item.model.js"), src("backend/helpers/finalPisCheck.js"), src("backend/services/validInspectionHistory.service.js")], certainty: "verified" },
    { id: "stored_status_report_exceptions", description: "Monthly Shipments, Item Database running PO, and QC Vendor Shipping Performance currently prefilter stored orders.status. This is current executable behavior and a documented analytical risk, not the global status rule.", canonicalSource: "the three audited report implementations, pending business confirmation", sources: [src("backend/services/monthlyShipmentsReport.service.js"), src("backend/controllers/item.controller.js"), src("backend/controllers/qc.controller.js")], certainty: "verified" },
    { id: "shipment_rows_physical_evidence", description: "Physical shipment evidence is embedded under orders or samples. Current Shipment rows can also emit progressed-order placeholders, which must not be described as physical shipments.", canonicalSource: "embedded shipment entries plus explicit placeholder provenance", sources: [src("backend/controllers/order.controller.js", "getShipmentDataset"), src("backend/models/order.model.js"), src("backend/models/sample.model.js")], certainty: "verified" },
    { id: "vendor_reference_normalization", description: "Embedded vendor snapshots are normalized against vendors through vendorRef; preserve snapshot context while using vendor_id for identity joins.", canonicalSource: "backend/helpers/vendorRef.js", sources: [src("backend/helpers/vendorRef.js")], certainty: "verified" },
    { id: "workflow_live_state", description: "Workflow task live state comes from workflow_tasks; assignment/status/comment collections provide related history and evidence.", canonicalSource: "workflow_tasks", sources: [src("backend/models/workflow/Task.model.js"), src("backend/models/workflow/TaskStatusHistory.model.js")], certainty: "verified" },
    { id: "audit_not_live_state", description: "Audit log records are evidence of past operations and must not override live order/QC/item state.", canonicalSource: "live collections supersede audit collections", sources: [src("backend/models/orderEditLog.model.js"), src("backend/models/qcEditLog.model.js"), src("backend/models/pisUpdateLog.model.js")], certainty: "verified" },
  ],
  businessDefinitions: [
    { id: "purchase_order", term: "Purchase order (PO)", definition: "An order line in orders, identified operationally by order_id and item context.", sourceOfTruthRule: "orders_live_state", sources: [src("backend/models/order.model.js")], certainty: "verified" },
    { id: "packed_goods_definition", term: "Packed Goods", definition: "The page report shows qualifying passed Inspection history for a selected period, split into previously packed, this-period packed, total packed, and shipped quantity. Shipped quantity is separate from the remaining packed quantity. The Assistant capability retains separate current ready-to-ship semantics.", sourceOfTruthRule: "packed_goods_period_report", sources: [src("backend/services/packedGoodsPeriod.service.js", "buildPackedGoodsPeriodDataset"), src("backend/services/packedGoods.service.js", "buildPackedGoodsDataset")], certainty: "verified" },
    { id: "pending_inspection", term: "Pending inspection quantity", definition: "Order quantity minus passed QC quantity, capped at zero.", sourceOfTruthRule: "order_progress_derivation", sources: [src("backend/helpers/orderStatus.js", "deriveOrderProgress")], certainty: "verified" },
    { id: "inspected_unshipped", term: "Inspected-unshipped quantity", definition: "The passed quantity still not shipped, capped by the remaining order quantity.", sourceOfTruthRule: "order_progress_derivation", sources: [src("backend/helpers/orderStatus.js", "deriveOrderProgress")], certainty: "verified" },
    { id: "order_status", term: "Order status", definition: "Derived lifecycle status: Pending, Under Inspection, Inspection Done, Partial Shipped, or Shipped; Cancelled is only allowed by a zero-quantity compatibility option.", sourceOfTruthRule: "order_progress_derivation", sources: [src("backend/helpers/orderStatus.js")], certainty: "verified" },
    { id: "total_po_cbm", term: "Total PO CBM", definition: "Order-level CBM field. It is derived/cached and only a fallback when current item measurement calculations produce no CBM.", sourceOfTruthRule: "shipment_cbm_calculation", sources: [src("backend/models/order.model.js"), src("backend/services/shipmentCbmAllocation.service.js")], certainty: "verified" },
    { id: "pis", term: "PIS", definition: "Product Information Sheet data stored on Item PIS fields, including packaging-aware dimensions, barcodes, and calculated CBM.", sourceOfTruthRule: "item_measurement_hierarchy", sources: [src("backend/models/item.model.js"), src("docs/PIS_PD_MASTER_ITEM_FLOW.md")], certainty: "verified" },
    { id: "master_item_data", term: "Master item data", definition: "Accepted master measurement values on Item. Final PIS Check currently requires this evidence and does not fall back to PIS.", sourceOfTruthRule: "item_measurement_hierarchy", sources: [src("backend/models/item.model.js"), src("backend/helpers/finalPisCheck.js")], certainty: "verified" },
    { id: "product_database", term: "Product Database", definition: "A separate Item pd_* and product_specs workflow with Created, Checked, and Approved state; it is not the PIS mismatch reference.", sourceOfTruthRule: "item_measurement_hierarchy", sources: [src("backend/helpers/productDatabase.js"), src("docs/PIS_PD_MASTER_ITEM_FLOW.md")], certainty: "verified" },
    { id: "qc_request", term: "QC request", definition: "A qcs document containing order metadata snapshot, requested quantities, request history, and inspections.", sourceOfTruthRule: "quality_live_state", sources: [src("backend/models/qc.model.js")], certainty: "verified" },
    { id: "inspection", term: "Inspection", definition: "An inspections document tied to a QC record with visit/result status, quantities, measurements, and evidence.", sourceOfTruthRule: "quality_live_state", sources: [src("backend/models/inspection.model.js")], certainty: "verified" },
    { id: "vendor_snapshot", term: "Vendor snapshot", definition: "A normalized embedded vendor object retained on operational documents; vendor_id is the identity reference and name/country are document context.", sourceOfTruthRule: "vendor_reference_normalization", sources: [src("backend/helpers/vendorRef.js")], certainty: "verified" },
    { id: "workflow_task", term: "Workflow task", definition: "A workflow_tasks record containing the live task lifecycle, assignees, due date, hold/rework, and upload state.", sourceOfTruthRule: "workflow_live_state", sources: [src("backend/models/workflow/Task.model.js")], certainty: "verified" },
    { id: "audit_log", term: "Audit log", definition: "Historical evidence of a change or upload. It does not replace current live state.", sourceOfTruthRule: "audit_not_live_state", sources: [src("backend/models/orderEditLog.model.js"), src("backend/models/qcEditLog.model.js")], certainty: "verified" },
    { id: "shipping_pending", term: "Shipping Pending", definition: "Every active order line with unshipped quantity greater than zero, including rows whose packed quantity is zero.", sourceOfTruthRule: "order_progress_derivation", sources: [src("backend/controllers/order.controller.js", "buildShippingPendingDataset"), src("backend/helpers/orderStatus.js")], certainty: "verified" },
    { id: "physical_shipment", term: "Physical shipment", definition: "An embedded shipment entry under an Order or Sample. A progressed-order placeholder emitted by the Shipment report is not physical shipment evidence.", sourceOfTruthRule: "shipment_rows_physical_evidence", sources: [src("backend/controllers/order.controller.js", "getShipmentDataset")], certainty: "verified" },
  ],
  aliases: legacyAliases,
  businessConceptMappings,
  ambiguousConcepts,
  uncertainties,
  legacyData: [
    { id: "vendor_embedded_snapshots", description: "Orders, QC, samples, complaints, and email logs retain embedded vendor snapshots. Normalize identity through vendor_id but preserve historical name/country snapshot context.", migration: "backend/scripts/backfill-vendor-objects.js", sources: [src("backend/helpers/vendorRef.js"), src("backend/scripts/backfill-vendor-objects.js")], certainty: "verified" },
    { id: "item_barcode_aliases", description: "PIS/master/QC barcode aliases are synchronized for compatibility; prefer the named current field set for the operating surface and do not assume all legacy aliases mean identical provenance.", sources: [src("backend/models/item.model.js"), src("backend/models/qc.model.js"), src("backend/scripts/updatePISbarcode.js")], certainty: "verified" },
    { id: "legacy_measurement_fields", description: "Array-backed measurements are preferred, with legacy LBH/weight fields still used as documented fallbacks in comparison and CBM flows.", migration: "backend/scripts/cleanupLegacyItemSizeFields.js", sources: [src("backend/models/item.model.js"), src("backend/helpers/finalPisCheck.js"), src("docs/MEASUREMENT_MISMATCH_COMPARISON_FLOW.md")], certainty: "verified" },
    { id: "stored_order_cbm", description: "orders.total_po_cbm is retained and backfilled but is a derived/cache fallback after current measurement-based CBM calculation.", migration: "backend/scripts/backfillTotalPoCbm.js", sources: [src("backend/services/orderCbm.service.js"), src("backend/services/shipmentCbmAllocation.service.js"), src("backend/scripts/backfillTotalPoCbm.js")], certainty: "verified" },
    { id: "historical_inspection_snapshots", description: "Inspection snapshots preserve historical measurement evidence for QC Report Mismatch; they are not automatically equivalent to the current Item inspected fields.", migration: "backend/scripts/backfillInspectionSizeSnapshots.js", sources: [src("backend/helpers/inspectionSizeSnapshot.js"), src("backend/scripts/backfillInspectionSizeSnapshots.js")], certainty: "verified" },
  ],
  auditFindings: [
    { id: "packed_goods_shared_service", severity: "informational", description: "Packed Goods has two intentional contracts: the page/API/export inspection-period report and the unchanged Assistant/forecast current-ready dataset.", sources: [src("backend/services/packedGoodsPeriod.service.js", "buildPackedGoodsPeriodDataset"), src("backend/services/packedGoods.service.js", "buildPackedGoodsDataset")], certainty: "verified" },
    { id: "packed_goods_frontend_presentation", severity: "informational", description: "PackedGoods.jsx sends its filters to the period-report API and only sorts/paginates returned rows; totals and filter options remain backend-owned.", sources: [src("client/OMS/src/pages/PackedGoods.jsx"), src("backend/services/packedGoodsPeriod.service.js")], certainty: "verified" },
    { id: "frontend_shipping_status_derivation", severity: "review", description: "Client shipping-report utilities derive grouped PO presentation status. Step 2 should use backend orderStatus helpers for Assistant-facing semantics.", sources: [src("client/OMS/src/utils/shippingPendingReport.js"), src("backend/helpers/orderStatus.js")], certainty: "strongly_inferred" },
    { id: "stored_cbm_fallback", severity: "warning", description: "Stored total_po_cbm can differ from current measurement-based CBM and must be labelled as fallback/cached when used.", sources: [src("backend/services/shipmentCbmAllocation.service.js")], certainty: "verified" },
    { id: "api_map_static_limits", severity: "informational", description: "api-map.md and api-map.xlsx are static route/client-use analysis aids, not a substitute for route/controller source tracing.", sources: [src("docs/api-map.md"), src("docs/api-map.xlsx")], certainty: "verified" },
    { id: "email_logs_router_unmounted", severity: "critical", description: "Email Logs router/controller/UI exist, but backend/index.js does not mount the router; intended /email-logs reads currently 404 and permission policy is unresolved.", sources: [src("backend/routers/emailLogs.routes.js"), src("backend/controllers/emailLogs.controller.js"), src("backend/index.js"), src("client/OMS/src/pages/EmailLogs.jsx")], certainty: "verified" },
    { id: "delayed_po_export_overridden", severity: "high", description: "order.controller assigns exportDelayedPoReport twice; the later reformed export overrides the earlier richer implementation and the definitions differ.", sources: [src("backend/controllers/order.controller.js", "exportDelayedPoReport", "buildReformedDelayedPoReportDataset")], certainty: "verified" },
    { id: "stored_status_report_dependencies", severity: "high", description: "Monthly Shipments, Item Database running PO, and QC Vendor Shipping Performance prefilter stored orders.status despite the global derived-status rule.", sources: [src("backend/services/monthlyShipmentsReport.service.js"), src("backend/controllers/item.controller.js"), src("backend/controllers/qc.controller.js")], certainty: "verified" },
    { id: "delay_definitions_differ", severity: "high", description: "Delayed PO, Shipping Delay, and frontend overdue-pending are different executable definitions and must not share one implicit intent.", sources: [src("backend/controllers/order.controller.js"), src("client/OMS/src/utils/shippingPendingReport.js")], certainty: "verified" },
    { id: "final_pis_current_contract", severity: "high", description: "Final PIS Check compares Inspected versus Master, requires three distinct valid inspected POs, and implements no PIS fallback; internal pis_* keys can contain Master values.", sources: [src("backend/controllers/item.controller.js"), src("backend/helpers/finalPisCheck.js"), src("backend/services/validInspectionHistory.service.js")], certainty: "verified" },
    { id: "shipment_filter_wiring", severity: "medium", description: "The shared shipment builder supports stuffing-date filters, but Shipment API/export callers do not pass them while Containers does.", sources: [src("backend/controllers/order.controller.js", "getShipmentDataset", "getShipmentsDb", "getContainerDataset")], certainty: "verified" },
    { id: "mismatch_tolerance_document_drift", severity: "medium", description: "Static mismatch documentation says 1 cm for item dimensions while executable comparison code uses a greater-than-0.5-cm threshold.", sources: [src("docs/MEASUREMENT_MISMATCH_COMPARISON_FLOW.md"), src("backend/helpers/measurementMismatchRules.js")], certainty: "verified" },
  ],
};

const validation = validateKnowledgeBase(catalog);
if (!validation.valid) {
  throw new Error(`Invalid OMS Knowledge Base catalog: ${validation.errors.join("; ")}`);
}

module.exports = freeze(catalog);
