module.exports = Object.freeze({
  IMPORT_ORDERS_FROM_FILE: "IMPORT_ORDERS_FROM_FILE",
  PROCESS_PIS_FILE: "PROCESS_PIS_FILE",
  CONVERT_PIS_TO_PDF: "CONVERT_PIS_TO_PDF",
  UPLOAD_TO_WASABI: "UPLOAD_TO_WASABI",
  SYNC_ORDER_GROUP_CALENDAR: "SYNC_ORDER_GROUP_CALENDAR",
  RESYNC_BRAND_CALENDAR: "RESYNC_BRAND_CALENDAR",
  RECALCULATE_ORDER_CBM: "RECALCULATE_ORDER_CBM",
  RECALCULATE_ALL_ORDER_CBM: "RECALCULATE_ALL_ORDER_CBM",
  OPTIMIZE_QC_IMAGES: "OPTIMIZE_QC_IMAGES",
});
